controller_list:
  - name: whi_arm_interface/controllers/scaled_pos_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: jaka_zu5
    pose: home
